// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqbiw8Q1CoS5yfX9xkD-1dTOMtd6MrX5I',
    appId: '1:300486860838:web:6dbeeaa3e39840b1e806e7',
    messagingSenderId: '300486860838',
    projectId: 'fixit-3db56',
    authDomain: 'fixit-3db56.firebaseapp.com',
    storageBucket: 'fixit-3db56.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvLTQGqSuUqgMPQPF3B5BkW1vgF3ZovRI',
    appId: '1:300486860838:android:fdc9cb929a12ae94e806e7',
    messagingSenderId: '300486860838',
    projectId: 'fixit-3db56',
    storageBucket: 'fixit-3db56.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdvx2KghNHJNm3bgzOZ7Vot80CLyNz4zw',
    appId: '1:300486860838:ios:24a26c04d84d2048e806e7',
    messagingSenderId: '300486860838',
    projectId: 'fixit-3db56',
    storageBucket: 'fixit-3db56.firebasestorage.app',
    iosBundleId: 'com.ralfiz.fixit',
  );
}
